name: Compilar APK Steelmat
on: [push, workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar compiladores C++ y dependencias de Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libbz2-dev libreadline-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libpcap-dev xz-utils libffi-dev build-essential g++ clang

      - name: Instalar Buildozer y Cython
        run: |
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Compilar con Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer android debug

      - name: Subir Instalador APK
        uses: actions/upload-artifact@v4
        with:
          name: Steelmat-Presupuestador-Celular
          path: bin/*.apk
